from enum import StrEnum, auto


class Symbol(StrEnum):
    BTC = auto()
    ETH = auto()
    BCH = auto()
    XRP = auto()
    EOS = auto()
    LTC = auto()
    TRX = auto()
    ETC = auto()
    LINK = auto()
    XLM = auto()
    ADA = auto()
    XMR = auto()
    DASH = auto()
    ZEC = auto()
    XTZ = auto()
    BNB = auto()
    ATOM = auto()
    ONT = auto()
    IOTA = auto()
    BAT = auto()
    VET = auto()
    NEO = auto()
    QTUM = auto()
    IOST = auto()
    THETA = auto()
    ALGO = auto()
    ZIL = auto()
    KNC = auto()
    ZRX = auto()
    COMP = auto()
    OMG = auto()
    DOGE = auto()
    SXP = auto()
    KAVA = auto()
    BAND = auto()
    RLC = auto()
    WAVES = auto()
    MKR = auto()
    SNX = auto()
    DOT = auto()
    DEFI = auto()
    YFI = auto()
    BAL = auto()
    CRV = auto()
    TRB = auto()
    RUNE = auto()
    SUSHI = auto()
    SRM = auto()
    EGLD = auto()
    SOL = auto()
    ICX = auto()
    STORJ = auto()
    BLZ = auto()
    UNI = auto()
    AVAX = auto()
    FTM = auto()
    HNT = auto()
    ENJ = auto()
    FLM = auto()
    TOMO = auto()
    REN = auto()
    KSM = auto()
    NEAR = auto()
    AAVE = auto()
    FIL = auto()
    RSR = auto()
    LRC = auto()
    MATIC = auto()
    OCEAN = auto()
    CVC = auto()
    BEL = auto()
    CTK = auto()
    AXS = auto()
    ALPHA = auto()
    ZEN = auto()
    SKL = auto()
    GRT = auto()
    # 1INCH = auto()
    CHZ = auto()
    SAND = auto()
    ANKR = auto()
    BTS = auto()
    LIT = auto()
    UNFI = auto()
    REEF = auto()
    RVN = auto()
    SFP = auto()
    XEM = auto()
    COTI = auto()
    CHR = auto()
    MANA = auto()
    ALICE = auto()
    HBAR = auto()
    ONE = auto()
    LINA = auto()
    STMX = auto()
    DENT = auto()
    CELR = auto()
    HOT = auto()
    MTL = auto()
    OGN = auto()
    NKN = auto()
    SC = auto()
    DGB = auto()
    # 1000SHIB = auto()
    BAKE = auto()
    GTC = auto()
    BTCDOM = auto()
    IOTX = auto()
    AUDIO = auto()
    RAY = auto()
    C98 = auto()
    MASK = auto()
    ATA = auto()
    DYDX = auto()
    # 1000XEC = auto()
    GALA = auto()
    CELO = auto()
    AR = auto()
    KLAY = auto()
    ARPA = auto()
    CTSI = auto()
    LPT = auto()
    ENS = auto()
    PEOPLE = auto()
    ANT = auto()
    ROSE = auto()
    DUSK = auto()
    FLOW = auto()
    IMX = auto()
    API3 = auto()
    GMT = auto()
    APE = auto()
    WOO = auto()
    FTT = auto()
    JASMY = auto()
    DAR = auto()
    GAL = auto()
    OP = auto()
    INJ = auto()
    STG = auto()
    FOOTBALL = auto()
    SPELL = auto()
    # 1000LUNC = auto()
    LUNA2 = auto()
    LDO = auto()
    CVX = auto()
    ICP = auto()
    APT = auto()
    QNT = auto()
    BLUEBIRD = auto()
    FET = auto()
    FXS = auto()
    HOOK = auto()
    MAGIC = auto()
    T = auto()
    RNDR = auto()
    HIGH = auto()
    MINA = auto()
    ASTR = auto()
    AGIX = auto()
    PHB = auto()
    GMX = auto()
    CFX = auto()
    STX = auto()
    COCOS = auto()
    BNX = auto()
    ACH = auto()
    SSV = auto()
    CKB = auto()
    PERP = auto()
    TRU = auto()
    LQTY = auto()
    USDC = auto()
    ID = auto()
    ARB = auto()
    JOE = auto()
    TLM = auto()
    AMB = auto()
    LEVER = auto()
    RDNT = auto()
    HFT = auto()
    XVS = auto()
    BLUR = auto()
    EDU = auto()
    IDEX = auto()
    SUI = auto()
    # 1000PEPE = auto()
    # 1000FLOKI = auto()
    UMA = auto()
    RAD = auto()
    KEY = auto()
    COMBO = auto()
    NMR = auto()
    MAV = auto()
    MDT = auto()
    XVG = auto()
    WLD = auto()
    PENDLE = auto()
    ARKM = auto()
    AGLD = auto()
    YGG = auto()
    DODOX = auto()
    BNT = auto()
    OXT = auto()
    SEI = auto()
    CYBER = auto()
    HIFI = auto()
    ARK = auto()
    FRONT = auto()
    GLMR = auto()
    BICO = auto()
    STRAX = auto()
    LOOM = auto()
    BIGTIME = auto()
    BOND = auto()
    ORBS = auto()
    STPT = auto()
    WAXP = auto()
    BSV = auto()
    RIF = auto()
    POLYX = auto()
    GAS = auto()
    POWR = auto()
    SLP = auto()
    TIA = auto()
    SNT = auto()
    CAKE = auto()
    MEME = auto()
    TWT = auto()
    TOKEN = auto()
    ORDI = auto()
    STEEM = auto()
    BADGER = auto()
    ILV = auto()
    NTRN = auto()
    MBL = auto()
    KAS = auto()
    BEAMX = auto()
    # 1000BONK = auto()
    PYTH = auto()
    SUPER = auto()
    USTC = auto()
    ONG = auto()
    ETHW = auto()
    JTO = auto()
    # 1000SATS = auto()
    AUCTION = auto()
    # 1000RATS = auto()
    ACE = auto()
    MOVR = auto()
    NFP = auto()
    AI = auto()
    XAI = auto()

    def __str__(self) -> str:
        return f"{self.value.upper()}/USDT"

    def __repr__(self) -> str:
        return self.__str__()

    def __add__(self, o) -> str:
        if not isinstance(o, str):
            raise TypeError("Only string can be added to Symbol.")
        return self.__str__() + str(o)

    def find(self, value: str) -> int:
        return self.__str__().find(value)

    def split(self, value: str) -> list[str]:
        return self.__str__().split(value)

    @property
    def base_currency(self) -> str:
        return self.value.upper()

    @property
    def quote_currency(self) -> str:
        return "USDT"

    @staticmethod
    def decode(value: str | None) -> "Symbol":
        if not value:
            raise ValueError("Value is empty or None.")
        if ":" in value:
            value = value.split(":")[0]
        return Symbol(value.split("/")[0].lower())

    @staticmethod
    def top10() -> list["Symbol"]:  # market cap top 10 at 2021-01-03, except USDT
        return [
            Symbol.BTC,
            Symbol.ETH,
            Symbol.LTC,
            Symbol.XRP,
            Symbol.DOT,
            Symbol.BCH,
            Symbol.ADA,
            Symbol.BNB,
            Symbol.LINK,
        ]

    @staticmethod
    def all() -> list["Symbol"]:
        return list(Symbol)
